version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://sheepdog:sheeodogs123@db:5432/MeterDB

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: sheepdog
      POSTGRES_PASSWORD: sheeodogs123
      POSTGRES_DB: MeterDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
